<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Putri Nabilah">
<meta name="dcterms.date" content="2024-01-21">

<title>Pengaruh Kemiskinan terhadap Kriminalitas di Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Kemiskinan terhadap Kriminalitas di Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Putri Nabilah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 21, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia merupakan negara dengan jumlah penduduk terbesar keempat di dunia, yaitu dengan penduduk sekitar 270 juta jiwa pada tahun 2020. Dengan jumlah penduduk yang sangat banyak tidak dipungkiri bahwa Indonesia menghadapi berbagai permasalahan sosial. Salah satu masalah sosial yang masih menjadi masalah darurat di Indonesia adalah kemiskinan. Angka kemiskinan di Indonesia selalu meningkat setiap tahunnya.</p>
<p>Banyak sekali dampak negatif yang dapat terjadi jika angka kemiskinan suatu negara tinggi. Kriminalitas adalah salah satu contih dampak yang dapat timbul akibat adanya masalah sosial kemiskinan. Semakin tinggi angka kemiskinan yang ada maka angka kriminalitas juga dapat semakin tinggi.</p>
<p>Beberapa penelitian telah menunjukkan adanya hubungan antara kemiskinan dan kriminalitas, baik secara positif maupun negatif. Secara positif, kemiskinan dapat meningkatkan kriminalitas karena orang miskin cenderung melakukan tindakan kriminal untuk memenuhi kebutuhan hidupnya. Secara negative, kemiskinan dapat menurunkan kriminalitas karena orang miskin tidak memiliki akses atau sasaran yang menarik bagi pelaku kriminal.</p>
<p>Hubungan antara kemiskinan dan kriminalitas tidak selalu searah dan sederhana karena dipengaruhi oleh berbagai faktor lain, seperti budaya, agama, hokum, dan lingkungan. Oleh karena itu, penelitian ini bertujuan untuk menguji pengaruh kemiskinan terhadap tingkat kriminalitas di Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini menggunakan data kriminalitas, dan kemiskinan dari Badan Pusat Statistik (BPS) tahun 2022 untuk 36 provinsi di Indonesia. Objek yang digunakan terdiri dari dua variabel, yakni variabel x dari data kemiskinan dan variabel y dari data kriminalitas. Penelitian ini menguji pengaruh kemiskinan dan pengangguran terhadap kriminalitas di Indonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li><p>Apakah kemiskinan mempengaruhi kriminalitas di Indonesia ?</p></li>
<li><p>Bagaimana hubungan kemiskinan dan kriminalitas di Indonesia ?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk menganalisis pengaruh kemiskinan terhadap tingkat kriminalitas di Indonesia, dengan menggunakan data dari Badan Pusat Statistik, dari 36 provinsi di Indonesia. Manfaat dari penelitian ini adalah untuk memberikan informasi dan rekomendasi kepada pemerintah dan masyarakat tentang faktor-faktor yang mempengaruhi kriminalitas.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Kemiskinan</strong></p>
<p>Kemiskinan adalah sebuah masalah sosial yang erjadi ketika seseorang tidak mampu untuk memenuhi kebutuhan dasarnya seperti makanan, pakaian, tempat tinggal,, kesehatan, dan pendidikan. Kemiskinan terdiri dari dua jenis, yaitu kemiskinan absolut dan kemiskinan relatif. Ketika individu hidup di bawah suatu batas pendapatan yang ditetapkan oleh pemerintah atau lembaga internasional maka dapat disebut kemiskinan absolut. Ketika individu hidup di bawah standar kesejahteraan yang berlaku di masyarakat sekitarnya maka disebut kemiskinan relatif.</p>
<p>Kemiskinan sendiri pastinya berdampak negatif, baik bagi individu, keluarga, maupun masyarakat. Dampak tersebut antara lain adalah malnutrisi, penyakit, kematian dini, rendahnya kualitas pendidikan dan keterampilan, kurangnya kesempatan dan partisipasi sosial, meningkatnya kriminalitas dan kekerasan, serta kerusakan lingkungan dan sumber daya alam. Dalam mengatasi kemiskinan dibutuhkan upaya yang komprehensif, terpadu, dan berkelanjutan dari berbagai pihak.</p>
<p><strong>Kriminalitas</strong></p>
<p>Tindakan melanggar hukun yang berlaku di suatu wilayah disebut kriminalitas. Kerugian dari tindakan kriminalitas dapat dirasakan dari segi ekonomis, psikologis, maupun sosial. Pelaku dari tindakan kriminalitas sendiri disebut kriminal atau penjahat. Kriminal dapat diberikan sanksi hukum yang berupa denda, penjara, hingga yang paling berat hukuman mati.</p>
<p>Kemiskinan, pengangguran, ketidakadilan, pendidikan yang rendah, lingkungan yang buruk, pengaruh media, ataupun gangguan jiwa menjadi beberapa faktor penyebab seseorang atau kelompok melakukan tindakan kriminalitas. Selain itu, kriminalitas juga dapat disebabkan oleh faktor biologis, psikologis, atau sosiologis.</p>
<p>Tak dipungkiri dampak dari tindakan kriminalitas sangatlah luas dan merugikan bagi berbagai pihak. Kerugian tersebut dapat berupa ketakutan, kecemasan, trauma, kerugian materi, korban jiwa, kerusakan fasilitas umum, atau gangguan ketertiban dan keamanan. Untuk mencegah terjadinya kriminalitas diperlukan upaya dari berbagai pihak.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 2%">
<col style="width: 32%">
<col style="width: 17%">
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Provinsi</th>
<th>kemiskinan</th>
<th>kriminalitas</th>
<th>y</th>
<th>x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Aceh</td>
<td>15,43</td>
<td>41</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>2</td>
<td>Sumatera Utara</td>
<td>0,08740</td>
<td>71</td>
<td>0,00071</td>
<td>0,000874</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Sumatera Barat</td>
<td>7,23000</td>
<td>28</td>
<td>0,00041</td>
<td>0,07230</td>
</tr>
<tr class="even">
<td>4</td>
<td>Riau</td>
<td>6,6500</td>
<td>45</td>
<td>0,00045</td>
<td>0,0665</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Jambi</td>
<td>6,28</td>
<td>29</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>6</td>
<td>Sumatera Selatan</td>
<td>12,21</td>
<td>57</td>
<td>0,00057</td>
<td>0,122100</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Bengkulu</td>
<td>15,3</td>
<td>97</td>
<td>0,00041</td>
<td>0,15300</td>
</tr>
<tr class="even">
<td>8</td>
<td>Lampung</td>
<td>12,65</td>
<td>48</td>
<td>0,00048</td>
<td>0,1265</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Kepulauan Bangka B.</td>
<td>5,85</td>
<td>24</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>10</td>
<td>Kepulauan Riau</td>
<td>10,69</td>
<td>32</td>
<td>0,00032</td>
<td>0,106900</td>
</tr>
<tr class="odd">
<td>11</td>
<td>DKI Jakarta</td>
<td>4,44</td>
<td>277</td>
<td>0,00041</td>
<td>0,04440</td>
</tr>
<tr class="even">
<td>12</td>
<td>Jawa Barat</td>
<td>9,3</td>
<td>15</td>
<td>0,00015</td>
<td>0,0930</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Jawa Tengah</td>
<td>11,87</td>
<td>25</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>14</td>
<td>DI Yogyakarta</td>
<td>13,36</td>
<td>22</td>
<td>0,00022</td>
<td>0,133600</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Jawa Timur</td>
<td>13,98</td>
<td>26</td>
<td>0,00041</td>
<td>0,13980</td>
</tr>
<tr class="even">
<td>16</td>
<td>Banten</td>
<td>6,79</td>
<td>38</td>
<td>0,00038</td>
<td>0,0679</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Bali</td>
<td>5,5</td>
<td>34</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>18</td>
<td>Nusa Tenggara Barat</td>
<td>13,95</td>
<td>98</td>
<td>0,00098</td>
<td>0,139500</td>
</tr>
<tr class="odd">
<td>19</td>
<td>Nusa Tenggara Timur</td>
<td>23,76</td>
<td>57</td>
<td>0,00041</td>
<td>0,23760</td>
</tr>
<tr class="even">
<td>20</td>
<td>Kalimantan Barat</td>
<td>8,07</td>
<td>26</td>
<td>0,00026</td>
<td>0,0807</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Kalimantan Tengah</td>
<td>5,35</td>
<td>18</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>22</td>
<td>Kalimantan Selatan</td>
<td>4,72</td>
<td>27</td>
<td>0,00027</td>
<td>0,047200</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Kalimantan Timur</td>
<td>9,28</td>
<td>36</td>
<td>0,00041</td>
<td>0,09280</td>
</tr>
<tr class="even">
<td>24</td>
<td>Kalimantan Utara</td>
<td>8,74</td>
<td>31</td>
<td>0,00031</td>
<td>0,0874</td>
</tr>
<tr class="odd">
<td>25</td>
<td>Sulawesi Utara</td>
<td>10,38</td>
<td>39</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>26</td>
<td>Sulawesi Tengah</td>
<td>14,09</td>
<td>63</td>
<td>0,00063</td>
<td>0,140900</td>
</tr>
<tr class="odd">
<td>27</td>
<td>Sulawesi Selatan</td>
<td>11,91</td>
<td>41</td>
<td>0,00041</td>
<td>0,11910</td>
</tr>
<tr class="even">
<td>28</td>
<td>Sulawesi Tenggara</td>
<td>13,94</td>
<td>38</td>
<td>0,00038</td>
<td>0,1394</td>
</tr>
<tr class="odd">
<td>29</td>
<td>Gorontalo</td>
<td>23,73</td>
<td>51</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>30</td>
<td>Sulawesi Barat</td>
<td>12,1</td>
<td>37</td>
<td>0,00037</td>
<td>0,121000</td>
</tr>
<tr class="odd">
<td>31</td>
<td>Maluku</td>
<td>24,64</td>
<td>78</td>
<td>0,00041</td>
<td>0,24640</td>
</tr>
<tr class="even">
<td>32</td>
<td>Maluku Utara</td>
<td>6,55</td>
<td>23</td>
<td>0,00023</td>
<td>0,0655</td>
</tr>
<tr class="odd">
<td>33</td>
<td>Papua Barat</td>
<td>29,2</td>
<td>289</td>
<td>0,00041</td>
<td>0,154300</td>
</tr>
<tr class="even">
<td>34</td>
<td>Papua</td>
<td>34,49</td>
<td>94</td>
<td>0,00094</td>
<td>0,344900</td>
</tr>
</tbody>
</table>
<p>Data yang digunakan berupa data persentase penduduk miskin dan crime rate dari 36 provinsi di Indonesia tahun 2022 yang diambil dari Badan Pusat Statistik (BPS). Selanjutnya peneliti mengolah data sedemikian rupa dengan melakukan log terhadap kedua variabel, sehingga menghasilkan variabel x yang didapat dari persentase penduduk miskin dan variabel y dari persentase kriminalitas. Data inilah yang nantinya akan digunakan sebagai objek dari penelitian.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>kriminalitas<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/tugasmetopen/putri/kriminalitas.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kriminalitas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Provinsi         `Penduduk Miskin` `Crime Rate`       y        x
  &lt;chr&gt;                        &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;
1 Aceh                       15.4    41           0.00041 0.154   
2 Sumatera Utara              0.0874 71           0.00071 0.000874
3 Sumatera Barat              7.23   28           0.00041 0.0723  
4 Riau                        6.65   45           0.00045 0.0665  
5 Jambi                       6.28   29           0.00041 0.154   
6 Sumatera Selatan           12.2    57           0.00057 0.122   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>kriminalitas,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"#CD5555"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan kemiskinan dan kriminalitas"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"kemiskinan"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"kriminalitas"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang digunakan dalam penelitian ini berupa metode regresu univariat untuk menguji hubungan antara variabel dependen dan variabel independent. Objek yang digunakan berupa variabel x (kemiskinan) dan variabel y (kriminalitas). Dengan ini peneliti dapat mengetahui seberapa besar pengaruh kemiskinan teradap pengangguran di Indonesia. Dengan spesifikasi yang dilakukan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah kriminalitas dan <span class="math inline">\(x_t\)</span> adalah kemiskinan.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>t value</th>
<th>Pr&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>3.051e-04</td>
<td>4.780</td>
<td>3.76e-05</td>
</tr>
<tr class="even">
<td>x</td>
<td>9.698e-04</td>
<td>2.173</td>
<td>0.0373</td>
</tr>
</tbody>
</table>
<p>Dari hasil diatas, dimasukkan kedalam persamaan sehingga:</p>
<p><span class="math display">\[
y_{t}=\ 0.0003051 + \ 0.0009698 x +\mu_t
\]</span></p>
<p>Nilai dari koefisien x adalah 0.0009698 yang berarti jika nilai variabel kemiskinan naik satu satuan, maka nilai variabel kriminalitas naik sebesar 0.0009698 satuan. Sedangkan nilai koefisien intercept sebesar 0.0003051 yang berarti jika nilai variabel kemiskinan adalah nol, maka nilai variabel kriminalitas adalah 0.0003051.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>kriminalitas<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"kriminalitas.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>kriminalitas)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = kriminalitas)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.453e-04 -7.499e-05 -4.477e-05  2.979e-05  5.396e-04 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 3.051e-04  6.383e-05   4.780 3.76e-05 ***
x           9.698e-04  4.463e-04   2.173   0.0373 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001619 on 32 degrees of freedom
Multiple R-squared:  0.1286,    Adjusted R-squared:  0.1013 
F-statistic: 4.721 on 1 and 32 DF,  p-value: 0.03732</code></pre>
</div>
</div>
<p>Niali dari Multiple R-squared sebesar 0.1286, yang menunjukkan bahwa variabel kemiskinan dapat menjelaskan variasi variabel kriminalitas sebesar 12.86%. Sedangkan Adjusted R-squared sebesar 0.1013, yang menunjukkan bahwa variabel kemiskinan dapat menjelaskan variasi variabel kriminalitas sebesar 10.13%. P-value yang ditunjukkan sebesar 0.03732 yang berarti lebih kecil dari tingkat signifikansi 5% (yaitu 0.05). Hal ini menunjukkan bahwa model regresi secara keseluruhan meskipun kecil, masih memiliki pengaruh yang signifikan terhadap variabel kriminalitas.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Hasil regresi menunjukkan bahwa variabel kemiskinan memiliki pengaruh yang positif dan signifikan terhadap variabel kriminalitas, hal ini dibuktikan dengan nilai koefisien x sebesar 0.0009698 yang menunjukkan nilai positif dan p sebesar 0.0373 yang masih menunjukkan signifikansi. Namun dilihat dari pengaruh yang kecil, masih ada variabel-variabel yang perlu diperhtikan seprti Pendidikan, lingkungan, sosial, bahkan mungkin media”.</p>
<p>Kemiskinan dapat menyiptakan ketidak setaraan sosial dan ekonomi di Masyarakat, hal itu dapat menimbulkan rasa ketidakpuasan pada individu yang hidup dalam kemiskinan. Maka hal ini dapat memicu tindakan kriminal sebagai bentuk penyelesaian masalah atau pencarian keadilan.</p>
<p>Kemiskinan dapat menjadi penghalang bagi individu untuk mendapatkan pendidikan yang memadai, yang dapat mempengaruhi kualitas dan stabilitas hidup mereka. Tanpa pendidikan yang memadai, individu mungkin merasa terpinggirkan dan sulit memperoleh pekerjaan yang layak. Hal ini juga dapat memicu individu untuk terlibat dalam tindakan kriminal.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Mardiyansyah, A. A., &amp; Ni, M. S. (2020). Ketimpangan Ekonomi, Kemiskinan Dan Akses Informasi: Bagaimana Pengaruhnya Terhadap Kriminalitas Di Indonesia. Jurnal Ekonika: Jurnal Ekonomi Universitas Kadiri, 5(1).</p>
<p>Dulkiah, M. Pengaruh Kemiskinan Terhadap Tingkat Tindak Kriminalitas Di Kota Bandung. Jurnal Ilmu Sosial dan Ilmu Politik UIN Sunan Gunung Djati Bandung, 8(1), 433887.</p>
<p>Sari, N. C., &amp; Azhar, Z. (2019). Analisis Kausalitas Kriminalitas, Pendidikan dan Kemiskinan di Indonesia. Jurnal Kajian Ekonomi dan Pembangunan, 1(2), 635-644.</p>
<p>Fachrurrozi, K., Fahmiwati, F., Hakim, L., Aswadi, A., &amp; Lidiana, L. (2021). Pengaruh Kemiskinan dan Pengangguran Terhadap Kriminalitas di Indonesia Di Tahun 2019. Jurnal Real Riset, 3(2), 173-178.</p>
<p>Rahmi, M., &amp; Adry, M. R. (2018). Pengaruh tingkat putus sekolah, kemiskinan dan pengangguran terhadap kriminalitas di Indonesia. Ecosains: Jurnal Ilmiah Ekonomi dan Pembangunan, 7(2), 147-154.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>